/**
 * LLM Service for generating slide plan JSON
 * Generates a strict slide-plan with layout + placeholder content only
 */

/**
 * Generate a slide plan from text input
 * @param {string} text - The input text to convert to slides
 * @param {string} apiKey - OpenAI API key (optional, uses mock if not provided)
 * @returns {Promise<Object>} Slide plan JSON
 */
export async function generateSlidePlan(text, apiKey) {
  if (apiKey) {
    return await generateWithOpenAI(text, apiKey);
  } else {
    return generateMockSlidePlan(text);
  }
}

/**
 * Generate slide plan using OpenAI API
 */
async function generateWithOpenAI(text, apiKey) {
  const systemPrompt = `You are a slide deck architect. Generate a strict JSON slide plan with the following structure:
{
  "slides": [
    {
      "layoutType": "title" | "content" | "two-column" | "section",
      "placeholders": {
        "title": "text content",
        "subtitle": "text content",
        "content": "text content",
        "leftColumn": "text content",
        "rightColumn": "text content"
      }
    }
  ]
}

Rules:
1. Each slide must specify a layoutType from: title, content, two-column, section
2. Only include placeholders that exist in the layout
3. Content must be concise and fit layout constraints
4. title layout: title, subtitle
5. content layout: title, content
6. two-column layout: title, leftColumn, rightColumn
7. section layout: title only
8. Return ONLY valid JSON, no markdown or explanations`;

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4-0613',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Convert this text to a slide plan:\n\n${text}` }
        ],
        temperature: 0.7,
        max_tokens: 2000
      })
    });

    if (!response.ok) {
      const statusCode = response.status;
      let errorMessage;
      
      switch (statusCode) {
        case 401:
          errorMessage = 'Invalid API key. Please check your OpenAI API key.';
          break;
        case 429:
          errorMessage = 'Rate limit exceeded. Please try again in a few moments.';
          break;
        case 500:
        case 502:
        case 503:
          errorMessage = 'OpenAI service is temporarily unavailable. Please try again later.';
          break;
        default:
          errorMessage = `OpenAI API error (${statusCode}): ${response.statusText}`;
      }
      
      throw new Error(errorMessage);
    }

    const data = await response.json();
    const content = data.choices[0].message.content.trim();
    
    // Parse JSON from response (remove markdown code blocks if present)
    const jsonMatch = content.match(/```json\s*([\s\S]*?)\s*```/) || content.match(/\{[\s\S]*\}/);
    const jsonStr = jsonMatch ? (jsonMatch[1] || jsonMatch[0]) : content;
    
    const slidePlan = JSON.parse(jsonStr);
    
    // Validate the parsed slide plan structure
    if (!slidePlan || !slidePlan.slides || !Array.isArray(slidePlan.slides)) {
      throw new Error('Invalid slide plan structure returned from OpenAI');
    }
    
    return slidePlan;
  } catch (error) {
    console.error('OpenAI API error:', error);
    if (error.message.includes('API key') || error.message.includes('Rate limit') || error.message.includes('unavailable')) {
      throw error; // Re-throw user-friendly errors
    }
    throw new Error(`Failed to generate slide plan with OpenAI: ${error.message}`);
  }
}

/**
 * Generate mock slide plan for testing without API key
 */
function generateMockSlidePlan(text) {
  // Simple heuristic: split by double newlines for sections
  const sections = text.split(/\n\n+/).filter(s => s.trim());
  
  const slides = [];
  
  // First slide is always a title slide
  if (sections.length > 0) {
    const firstSection = sections[0].split('\n')[0].trim();
    slides.push({
      layoutType: 'title',
      placeholders: {
        title: firstSection || 'Presentation Title',
        subtitle: 'Generated by SlideArchitect'
      }
    });
  }
  
  // Process remaining sections
  for (let i = 0; i < sections.length; i++) {
    const section = sections[i];
    const lines = section.split('\n').map(l => l.trim()).filter(l => l);
    
    if (lines.length === 0) continue;
    
    // Check if it's a title: pattern
    const titleMatch = lines[0].match(/^(?:title|heading|section):\s*(.+)$/i);
    if (titleMatch && i > 0) {
      slides.push({
        layoutType: 'section',
        placeholders: {
          title: titleMatch[1]
        }
      });
      continue;
    }
    
    // Check if it has bullet points or multiple lines (content slide)
    if (lines.length > 1 || i > 0) {
      const title = lines[0];
      const content = lines.slice(1).join('\n');
      
      // Determine if content is too long and needs splitting
      if (content.length > 500) {
        // Split into two columns
        const midPoint = Math.floor(content.length / 2);
        const splitPoint = content.indexOf('\n', midPoint);
        const actualSplit = splitPoint > 0 ? splitPoint : midPoint;
        
        slides.push({
          layoutType: 'two-column',
          placeholders: {
            title: title,
            leftColumn: content.substring(0, actualSplit).trim(),
            rightColumn: content.substring(actualSplit).trim()
          }
        });
      } else {
        slides.push({
          layoutType: 'content',
          placeholders: {
            title: title,
            content: content || ''
          }
        });
      }
    }
  }
  
  // Ensure we have at least one slide
  if (slides.length === 0) {
    slides.push({
      layoutType: 'title',
      placeholders: {
        title: 'Generated Presentation',
        subtitle: 'Created from your text'
      }
    });
  }
  
  return { slides };
}
